services:

  keelson-network-manager:
    build: .
    container_name: keelson-network-manager
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    command: "--log-level 10 --realm rise --entity-id ted --trigger ping_up_down --ping-common-key rise/v0/boatswain"